/* 
 *  Copyright 2022 VMware, Inc.
 *  
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *  http://www.apache.org/licenses/LICENSE-2.0
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"github.com/vmware-tanzu/app-migrator-for-cloud-foundry/pkg/context"
)

type FakeAppImportRunner struct {
	RunStub        func(*context.Context) error
	runMutex       sync.RWMutex
	runArgsForCall []struct {
		arg1 *context.Context
	}
	runReturns struct {
		result1 error
	}
	runReturnsOnCall map[int]struct {
		result1 error
	}
	SetAppNameStub        func(string)
	setAppNameMutex       sync.RWMutex
	setAppNameArgsForCall []struct {
		arg1 string
	}
	SetOrgNameStub        func(string)
	setOrgNameMutex       sync.RWMutex
	setOrgNameArgsForCall []struct {
		arg1 string
	}
	SetSpaceNameStub        func(string)
	setSpaceNameMutex       sync.RWMutex
	setSpaceNameArgsForCall []struct {
		arg1 string
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeAppImportRunner) Run(arg1 *context.Context) error {
	fake.runMutex.Lock()
	ret, specificReturn := fake.runReturnsOnCall[len(fake.runArgsForCall)]
	fake.runArgsForCall = append(fake.runArgsForCall, struct {
		arg1 *context.Context
	}{arg1})
	stub := fake.RunStub
	fakeReturns := fake.runReturns
	fake.recordInvocation("Run", []interface{}{arg1})
	fake.runMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAppImportRunner) RunCallCount() int {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	return len(fake.runArgsForCall)
}

func (fake *FakeAppImportRunner) RunCalls(stub func(*context.Context) error) {
	fake.runMutex.Lock()
	defer fake.runMutex.Unlock()
	fake.RunStub = stub
}

func (fake *FakeAppImportRunner) RunArgsForCall(i int) *context.Context {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	argsForCall := fake.runArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAppImportRunner) RunReturns(result1 error) {
	fake.runMutex.Lock()
	defer fake.runMutex.Unlock()
	fake.RunStub = nil
	fake.runReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeAppImportRunner) RunReturnsOnCall(i int, result1 error) {
	fake.runMutex.Lock()
	defer fake.runMutex.Unlock()
	fake.RunStub = nil
	if fake.runReturnsOnCall == nil {
		fake.runReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.runReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeAppImportRunner) SetAppName(arg1 string) {
	fake.setAppNameMutex.Lock()
	fake.setAppNameArgsForCall = append(fake.setAppNameArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.SetAppNameStub
	fake.recordInvocation("SetAppName", []interface{}{arg1})
	fake.setAppNameMutex.Unlock()
	if stub != nil {
		fake.SetAppNameStub(arg1)
	}
}

func (fake *FakeAppImportRunner) SetAppNameCallCount() int {
	fake.setAppNameMutex.RLock()
	defer fake.setAppNameMutex.RUnlock()
	return len(fake.setAppNameArgsForCall)
}

func (fake *FakeAppImportRunner) SetAppNameCalls(stub func(string)) {
	fake.setAppNameMutex.Lock()
	defer fake.setAppNameMutex.Unlock()
	fake.SetAppNameStub = stub
}

func (fake *FakeAppImportRunner) SetAppNameArgsForCall(i int) string {
	fake.setAppNameMutex.RLock()
	defer fake.setAppNameMutex.RUnlock()
	argsForCall := fake.setAppNameArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAppImportRunner) SetOrgName(arg1 string) {
	fake.setOrgNameMutex.Lock()
	fake.setOrgNameArgsForCall = append(fake.setOrgNameArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.SetOrgNameStub
	fake.recordInvocation("SetOrgName", []interface{}{arg1})
	fake.setOrgNameMutex.Unlock()
	if stub != nil {
		fake.SetOrgNameStub(arg1)
	}
}

func (fake *FakeAppImportRunner) SetOrgNameCallCount() int {
	fake.setOrgNameMutex.RLock()
	defer fake.setOrgNameMutex.RUnlock()
	return len(fake.setOrgNameArgsForCall)
}

func (fake *FakeAppImportRunner) SetOrgNameCalls(stub func(string)) {
	fake.setOrgNameMutex.Lock()
	defer fake.setOrgNameMutex.Unlock()
	fake.SetOrgNameStub = stub
}

func (fake *FakeAppImportRunner) SetOrgNameArgsForCall(i int) string {
	fake.setOrgNameMutex.RLock()
	defer fake.setOrgNameMutex.RUnlock()
	argsForCall := fake.setOrgNameArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAppImportRunner) SetSpaceName(arg1 string) {
	fake.setSpaceNameMutex.Lock()
	fake.setSpaceNameArgsForCall = append(fake.setSpaceNameArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.SetSpaceNameStub
	fake.recordInvocation("SetSpaceName", []interface{}{arg1})
	fake.setSpaceNameMutex.Unlock()
	if stub != nil {
		fake.SetSpaceNameStub(arg1)
	}
}

func (fake *FakeAppImportRunner) SetSpaceNameCallCount() int {
	fake.setSpaceNameMutex.RLock()
	defer fake.setSpaceNameMutex.RUnlock()
	return len(fake.setSpaceNameArgsForCall)
}

func (fake *FakeAppImportRunner) SetSpaceNameCalls(stub func(string)) {
	fake.setSpaceNameMutex.Lock()
	defer fake.setSpaceNameMutex.Unlock()
	fake.SetSpaceNameStub = stub
}

func (fake *FakeAppImportRunner) SetSpaceNameArgsForCall(i int) string {
	fake.setSpaceNameMutex.RLock()
	defer fake.setSpaceNameMutex.RUnlock()
	argsForCall := fake.setSpaceNameArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAppImportRunner) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	fake.setAppNameMutex.RLock()
	defer fake.setAppNameMutex.RUnlock()
	fake.setOrgNameMutex.RLock()
	defer fake.setOrgNameMutex.RUnlock()
	fake.setSpaceNameMutex.RLock()
	defer fake.setSpaceNameMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeAppImportRunner) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ context.AppImportRunner = new(FakeAppImportRunner)
