/* 
 *  Copyright 2022 VMware, Inc.
 *  
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *  http://www.apache.org/licenses/LICENSE-2.0
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	cfclient "github.com/cloudfoundry-community/go-cfclient"
	"github.com/vmware-tanzu/app-migrator-for-cloud-foundry/pkg/context"
)

type FakeSpaceExporter struct {
	ExportSpaceStub        func(*context.Context, cfclient.Space, context.ProcessFunc) (<-chan context.ProcessResult, error)
	exportSpaceMutex       sync.RWMutex
	exportSpaceArgsForCall []struct {
		arg1 *context.Context
		arg2 cfclient.Space
		arg3 context.ProcessFunc
	}
	exportSpaceReturns struct {
		result1 <-chan context.ProcessResult
		result2 error
	}
	exportSpaceReturnsOnCall map[int]struct {
		result1 <-chan context.ProcessResult
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeSpaceExporter) ExportSpace(arg1 *context.Context, arg2 cfclient.Space, arg3 context.ProcessFunc) (<-chan context.ProcessResult, error) {
	fake.exportSpaceMutex.Lock()
	ret, specificReturn := fake.exportSpaceReturnsOnCall[len(fake.exportSpaceArgsForCall)]
	fake.exportSpaceArgsForCall = append(fake.exportSpaceArgsForCall, struct {
		arg1 *context.Context
		arg2 cfclient.Space
		arg3 context.ProcessFunc
	}{arg1, arg2, arg3})
	stub := fake.ExportSpaceStub
	fakeReturns := fake.exportSpaceReturns
	fake.recordInvocation("ExportSpace", []interface{}{arg1, arg2, arg3})
	fake.exportSpaceMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeSpaceExporter) ExportSpaceCallCount() int {
	fake.exportSpaceMutex.RLock()
	defer fake.exportSpaceMutex.RUnlock()
	return len(fake.exportSpaceArgsForCall)
}

func (fake *FakeSpaceExporter) ExportSpaceCalls(stub func(*context.Context, cfclient.Space, context.ProcessFunc) (<-chan context.ProcessResult, error)) {
	fake.exportSpaceMutex.Lock()
	defer fake.exportSpaceMutex.Unlock()
	fake.ExportSpaceStub = stub
}

func (fake *FakeSpaceExporter) ExportSpaceArgsForCall(i int) (*context.Context, cfclient.Space, context.ProcessFunc) {
	fake.exportSpaceMutex.RLock()
	defer fake.exportSpaceMutex.RUnlock()
	argsForCall := fake.exportSpaceArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeSpaceExporter) ExportSpaceReturns(result1 <-chan context.ProcessResult, result2 error) {
	fake.exportSpaceMutex.Lock()
	defer fake.exportSpaceMutex.Unlock()
	fake.ExportSpaceStub = nil
	fake.exportSpaceReturns = struct {
		result1 <-chan context.ProcessResult
		result2 error
	}{result1, result2}
}

func (fake *FakeSpaceExporter) ExportSpaceReturnsOnCall(i int, result1 <-chan context.ProcessResult, result2 error) {
	fake.exportSpaceMutex.Lock()
	defer fake.exportSpaceMutex.Unlock()
	fake.ExportSpaceStub = nil
	if fake.exportSpaceReturnsOnCall == nil {
		fake.exportSpaceReturnsOnCall = make(map[int]struct {
			result1 <-chan context.ProcessResult
			result2 error
		})
	}
	fake.exportSpaceReturnsOnCall[i] = struct {
		result1 <-chan context.ProcessResult
		result2 error
	}{result1, result2}
}

func (fake *FakeSpaceExporter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.exportSpaceMutex.RLock()
	defer fake.exportSpaceMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeSpaceExporter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ context.SpaceExporter = new(FakeSpaceExporter)
