/* 
 *  Copyright 2022 VMware, Inc.
 *  
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *  http://www.apache.org/licenses/LICENSE-2.0
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */

// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	cfclient "github.com/cloudfoundry-community/go-cfclient"
	"github.com/vmware-tanzu/app-migrator-for-cloud-foundry/pkg/context"
)

type FakeManifestExporter struct {
	ExportAppManifestStub        func(*context.Context, cfclient.Org, cfclient.Space, cfclient.App, string) error
	exportAppManifestMutex       sync.RWMutex
	exportAppManifestArgsForCall []struct {
		arg1 *context.Context
		arg2 cfclient.Org
		arg3 cfclient.Space
		arg4 cfclient.App
		arg5 string
	}
	exportAppManifestReturns struct {
		result1 error
	}
	exportAppManifestReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeManifestExporter) ExportAppManifest(arg1 *context.Context, arg2 cfclient.Org, arg3 cfclient.Space, arg4 cfclient.App, arg5 string) error {
	fake.exportAppManifestMutex.Lock()
	ret, specificReturn := fake.exportAppManifestReturnsOnCall[len(fake.exportAppManifestArgsForCall)]
	fake.exportAppManifestArgsForCall = append(fake.exportAppManifestArgsForCall, struct {
		arg1 *context.Context
		arg2 cfclient.Org
		arg3 cfclient.Space
		arg4 cfclient.App
		arg5 string
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.ExportAppManifestStub
	fakeReturns := fake.exportAppManifestReturns
	fake.recordInvocation("ExportAppManifest", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.exportAppManifestMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeManifestExporter) ExportAppManifestCallCount() int {
	fake.exportAppManifestMutex.RLock()
	defer fake.exportAppManifestMutex.RUnlock()
	return len(fake.exportAppManifestArgsForCall)
}

func (fake *FakeManifestExporter) ExportAppManifestCalls(stub func(*context.Context, cfclient.Org, cfclient.Space, cfclient.App, string) error) {
	fake.exportAppManifestMutex.Lock()
	defer fake.exportAppManifestMutex.Unlock()
	fake.ExportAppManifestStub = stub
}

func (fake *FakeManifestExporter) ExportAppManifestArgsForCall(i int) (*context.Context, cfclient.Org, cfclient.Space, cfclient.App, string) {
	fake.exportAppManifestMutex.RLock()
	defer fake.exportAppManifestMutex.RUnlock()
	argsForCall := fake.exportAppManifestArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeManifestExporter) ExportAppManifestReturns(result1 error) {
	fake.exportAppManifestMutex.Lock()
	defer fake.exportAppManifestMutex.Unlock()
	fake.ExportAppManifestStub = nil
	fake.exportAppManifestReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeManifestExporter) ExportAppManifestReturnsOnCall(i int, result1 error) {
	fake.exportAppManifestMutex.Lock()
	defer fake.exportAppManifestMutex.Unlock()
	fake.ExportAppManifestStub = nil
	if fake.exportAppManifestReturnsOnCall == nil {
		fake.exportAppManifestReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.exportAppManifestReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeManifestExporter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.exportAppManifestMutex.RLock()
	defer fake.exportAppManifestMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeManifestExporter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ context.ManifestExporter = new(FakeManifestExporter)
