#!/usr/bin/env bash

find_latest_semver() {
  pattern="^v([0-9]+\.[0-9]+\.[0-9]+)\$"
  versions=$(for tag in $(git tag); do
    [[ "$tag" =~ $pattern ]] && echo "${BASH_REMATCH[1]}"
  done)
  if [ -z "$versions" ];then
    echo 0.0.0
  else
    echo "$versions" | tr '.' ' ' | sort -nr -k 1 -k 2 -k 3 | tr ' ' '.' | head -1
  fi
}

increment_ver() {
  find_latest_semver | awk -F. -v a="$1" -v b="$2" -v c="$3" \
      '{printf("%d.%d.%d", $1+a, $2+b , $3+c)}'
}

show_next_patch_version() {
  echo "v$(increment_ver "0" "0" "1")"
}

show_next_patch_version